// Program.cs — WPF entry point is App.xaml (auto-generated by the WPF template).
// This file is kept only as a hook for console/debug runs if needed.
// Do NOT add [STAThread] / Application.Run() here — App.xaml handles that.

namespace CybersecurityChatbot
{
    internal static class Program
    {
        /// <summary>
        /// Optional console debug entry point.
        /// To use: temporarily change the project Output Type to Console Application,
        /// uncomment the lines below, then switch back to Windows Application for WPF.
        /// </summary>
        public static void StartConsoleChat()
        {
            // var mgr = new Utilities.ChatbotManager();
            // mgr.Start();
        }
    }
}
